variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - deploy
  - post_deploy

default:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  before_script:
    - apk add yarn

pages:
  stage: deploy
  script:
    - yarn
    - hugo version
    - hugo --minify
  artifacts:
    paths:
      - public
  only:
    - master

purge_cache:
  stage: post_deploy
  image: alpine
  before_script:
    - apk add curl
  script:
    - >
      curl
      -H "Authorization: Bearer $CLOUDFLARE_TOKEN"
      -H "Content-Type: application/json"
      --data '{"purge_everything":true}'
      -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache"
  only:
    - master
