image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo --minify
  except:
  - master

pages:
  script:
  - hugo --minify
  artifacts:
    paths:
    - public
  only:
  - master
