baseURL = "https://eikenberg.at/"
languageCode = "en-us"
title = "Raphael Eikenberg"
disableHugoGeneratorInject = true
enableRobotsTXT = true

# Do not include any taxonomies in sitemap.
[taxonomies]

[social]
	github = "eikendev"
	gitlab = "eikendev"
	linkedin = "raphael-eikenberg"
	twitter = "eikendev"

[params]
	title = "Raphael Eikenberg"
	author = "Raphael Eikenberg"
	description = "Just a few words about myself."
	keywords = "about, portfolio, eikendev"

# https://gohugo.io/templates/sitemap-template/
[sitemap]
	changefreq = "weekly"
	filename = "sitemap.xml"
	priority = 0.5
