baseURL = "https://www.eikenberg.at/"
languageCode = "en-us"
title = "Raphael Eikenberg"
disableHugoGeneratorInject = true
enableRobotsTXT = true

# Do not include any taxonomies in sitemap.
[taxonomies]

[social]
	twitter = "eikendev"
	mastodon = "https://infosec.exchange/@eikendev"
	github = "eikendev"
	linkedin = "raphael-eikenberg"

[params]
	title = "Raphael Eikenberg"
	author = "Raphael Eikenberg"
	description = "Just a few words about myself."
	keywords = "about, portfolio, eikendev"
	images = ["/img/card.png"]

# https://gohugo.io/templates/sitemap-template/
[sitemap]
	changefreq = "weekly"
	filename = "sitemap.xml"
	priority = 0.5
